// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: moviori.proto

package moviori_movies

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MovioriMoviesClient is the client API for MovioriMovies service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovioriMoviesClient interface {
	FindByName(ctx context.Context, in *FindMovieRequest, opts ...grpc.CallOption) (*FindMovieResponse, error)
}

type movioriMoviesClient struct {
	cc grpc.ClientConnInterface
}

func NewMovioriMoviesClient(cc grpc.ClientConnInterface) MovioriMoviesClient {
	return &movioriMoviesClient{cc}
}

func (c *movioriMoviesClient) FindByName(ctx context.Context, in *FindMovieRequest, opts ...grpc.CallOption) (*FindMovieResponse, error) {
	out := new(FindMovieResponse)
	err := c.cc.Invoke(ctx, "/Moviori_movies/FindByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovioriMoviesServer is the server API for MovioriMovies service.
// All implementations must embed UnimplementedMovioriMoviesServer
// for forward compatibility
type MovioriMoviesServer interface {
	FindByName(context.Context, *FindMovieRequest) (*FindMovieResponse, error)
	mustEmbedUnimplementedMovioriMoviesServer()
}

// UnimplementedMovioriMoviesServer must be embedded to have forward compatible implementations.
type UnimplementedMovioriMoviesServer struct {
}

func (UnimplementedMovioriMoviesServer) FindByName(context.Context, *FindMovieRequest) (*FindMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByName not implemented")
}
func (UnimplementedMovioriMoviesServer) mustEmbedUnimplementedMovioriMoviesServer() {}

// UnsafeMovioriMoviesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovioriMoviesServer will
// result in compilation errors.
type UnsafeMovioriMoviesServer interface {
	mustEmbedUnimplementedMovioriMoviesServer()
}

func RegisterMovioriMoviesServer(s grpc.ServiceRegistrar, srv MovioriMoviesServer) {
	s.RegisterService(&MovioriMovies_ServiceDesc, srv)
}

func _MovioriMovies_FindByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovioriMoviesServer).FindByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Moviori_movies/FindByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovioriMoviesServer).FindByName(ctx, req.(*FindMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovioriMovies_ServiceDesc is the grpc.ServiceDesc for MovioriMovies service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovioriMovies_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Moviori_movies",
	HandlerType: (*MovioriMoviesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByName",
			Handler:    _MovioriMovies_FindByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moviori.proto",
}
